### ISSUE TITLE
How To Use This tool Boss??

### ISSUE THREAD

**Issue by Nomanali3468** [Neo-1977/N0DE-DL#1]
i have clear keys and mpd url  DSTV can you tell me how can i restream mpd with clear key to hls

**Comment by Neo-1977** [comment]
If you don't fully understand how to install and have this working. Then also to replace what's needed within the manager's sections then I believe you should go back to using clearkey only within a player.

**Comment by Nomanali3468** [comment]
yeah i have found a way to play on android but i want to restream i have found a script on github which is A Simple DRM(CENC) decrypting script for DASH manifests of "dynamic" type Simple Dash DRM Livestream decrypt Proxy i have installed on my server but its not working with My Url i dont know why

**Comment by Nomanali3468** [comment]
here is script https://github.com/redmusicxd/dash_live_decrypt_proxy its a clear key script with mpd url but i have tried with my own mpd url with keys but its not working

**Comment by Nomanali3468** [comment]
> If you don't fully understand how to install and have this working. Then also to replace what's needed within the manager's sections then I believe you should go back to using clearkey only within a player.

i have also DSTV ACCOUNT And License Url please help

**Comment by Neo-1977** [comment]
You are asking things out of scope and other peoples code. No mention of you even able to get things to work on this code sample closing
